In [1]:
import numpy as np

np.full(10, 20)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [ ]:
arr = np.array([[
        [10, 20],
        [10, 20]
    ],[
        [5, 10],
        [8, 12],
    ]])

arr.flatten()

array([10, 20, 10, 20,  5, 10,  8, 12])

In [1]:
import numpy as np

x = np.array((3, 4, 5))
y = np.array((6, 7, 8))

stacked_array = np.column_stack((x, y))

print(stacked_array)


[[3 6]
 [4 7]
 [5 8]]


In [4]:
np.clip(4, 1e-4, 2)

np.float64(2.0)